# Generated by Django 3.0.4 on 2020-03-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='branch',
            name='gen_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='gen_capacity_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='gen_pwd_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='gen_pwd_capacity_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='obc_ncl_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='obc_ncl_capacity_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='obc_ncl_pwd_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='obc_ncl_pwd_capacity_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='sc_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='sc_capacity_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='sc_pwd_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='sc_pwd_capacity_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='st_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='st_capacity_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='st_pwd_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='st_pwd_capacity_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='freeze',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='removed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
    ]
