# Generated by Django 3.0.4 on 2020-03-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0003_auto_20200323_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
