# Generated by Django 3.0a1 on 2020-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0005_candidate_quota_for_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='preferences',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
