# Generated by Django 3.0a1 on 2020-04-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0006_auto_20200423_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='locked',
            field=models.IntegerField(default=0),
        ),
    ]
